# Generated by Django 4.1.4 on 2022-12-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_file_file_my_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='my_file',
            new_name='file',
        ),
    ]
