# Generated by Django 4.1.3 on 2022-12-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poste',
            new_name='Post',
        ),
    ]
